### PR TITLE
minor fix & small UI changes

### PR DESCRIPTION
**Pull request by latgit**

### CODE REVIEW

**Comment by sariaRiski02** [comment]
i disapprove your task as i have completed it. but maybe you can take a look in case you can find a bug in my code. ok guys we are learning together

**Comment by latgit** [comment]
conflict is resolved, you can do merge now.

**Review by sariaRiski02 — APPROVED** [review]

**Comment by sariaRiski02** [comment]
There is an update on the main branch you can see I have merged it on my local computer and I have pushed it on the main branch

**Review by sariaRiski02 — CHANGES_REQUESTED** [review]
This branch has been merged and has been completed. please try to check again

**Pull request closed without merging**
